### ISSUE TITLE
"Yo" animation - Safari

### ISSUE THREAD

**Issue by 45kb** [45kb/checkbox.css#5]
Strange behavior with Yo animation and Safari...

Macosx, El Captain 10.11.5

![senza-titolo](https://cloud.githubusercontent.com/assets/7761650/16294628/f15b7172-3921-11e6-8617-f23822710cb5.gif)

**Comment by equinusocio** [comment]
Fixed by adding `translateZ(0)`and force the advanced rendering:
![2016-06-28 23 07 57](https://cloud.githubusercontent.com/assets/10454741/16432420/350d9db6-3d85-11e6-8ee9-1e22f7459354.gif)

**Comment by 45kb** [comment]
Super @equinusocio 👍
